# Generated by Django 3.0 on 2019-11-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langapp', '0002_auto_20191129_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='email',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='phone_number',
        ),
    ]
